name: tennistournament
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http:
  provider:
  intl:
  curved_navigation_bar:
  diagonal_scrollview: ^0.1.0
  charts_flutter: ^0.6.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/fabian_torres_image.png
    - assets/img/fabian_torres_profile.png
    - assets/img/guillermo_pinus_image.png
    - assets/img/guillermo_pinus_profile.png
    - assets/img/leonardo_pace_image.png
    - assets/img/leonardo_pace_profile.png
    - assets/img/luis_guerci_image.png
    - assets/img/luis_guerci_profile.png
    - assets/img/matias_zemborain_image.png
    - assets/img/matias_zemborain_profile.png
    - assets/img/pablo_santacruz_image.png
    - assets/img/pablo_santacruz_profile.png
    - assets/img/damian_giusti_image.png
    - assets/img/damian_giusti_profile.png
    - assets/img/ignacio_zazu_image.png
    - assets/img/ignacio_zazu_profile.png
    - assets/img/jorge_barbe_image.png
    - assets/img/jorge_barbe_profile.png
    - assets/img/gustavo_carbonari_profile.png
    - assets/img/gustavo_carbonari_image.png
    - assets/img/mariano_moll_profile.png
    - assets/img/mariano_moll_image.png
    - assets/img/ignacio_lauret_image.png
    - assets/img/ignacio_lauret_profile.png
    - assets/img/argentina_flag.png
    - assets/img/default_match.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSans-Italic.ttf
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
