/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData tennis_education = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_calendar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData versus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_player = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_rules = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_court_big_ball = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_court = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_championship = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podium = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_bounce = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
